name: GitHub Release

on:
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt install tofrodos gcc-mingw-w64 libz-mingw-w64-dev
    - name: make
      run: make iodine-latest-windows.zip
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: iodine-latest-windows.zip
        path: iodine-latest-windows.zip
        retention-days: 5

  build-darwin:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: install check
      run: brew install check
    - name: run tests
      run: make test
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: iodine-latest-macos-amd64
        path: bin/*
        retention-days: 5

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: iodine-latest-linux-amd64
        path: bin/*
        retention-days: 5


  release:
    needs: [build-linux, build-darwin, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.tag.outputs.tag}}
          release_name: ${{steps.tag.outputs.tag}}
          draft: true
          prerelease: false
      - name: ls
        run: |
          ls -la
          pwd
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./
          asset_name: iodine-latest-windows.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./
          asset_name: iodine-latest-linux-amd64
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./
          asset_name: iodine-latest-macos-amd64
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
