name: windows_package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt install tofrodos gcc-mingw-w64 libz-mingw-w64-dev
    - name: make
      run: make iodine-latest-windows.zip
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: iodine-latest-windows.zip
        path: iodine-latest-windows.zip
        retention-days: 5
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.tag.outputs.tag}}
        release_name: ${{steps.tag.outputs.tag}}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./iodine-latest-windows.zip
        asset_name: iodine-latest-windows.zip
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
